name: eva_event_service
description: A sample command-line application.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  eva_sdk: ^0.4.0
  path: ^1.9.0
  postgres: ^3.5.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
